spring:
  application:
    name: pastebin-notifications-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: vvaa3174@gmail.com
    password: kvjcotnzlaymhwml
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: pastebin_user
    password: pastebin_passwordg
    queues:
      verification-code: verification-code.queue
      register-notification: register-notification.queue
    exchanges:
      verification-code: verification-code.internal.queue
      register-notification: register-notification.internal.queue
    routing-keys:
      verification-code: verification-code.internal.routing-key
      register-notification: register-notification.internal.routing-key
server:
  port: 8081
  error:
    whitelabel:
      enabled: false